apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ecolibrium-app.fullname" . }}-config
data:
  APP_ENV: "dev"
  APP_MESSAGE: "Hello from ConfigMap"
  index.html: |
    <h1>Ecolibrium DevOps Assignment</h1>
    <p>App is running on EKS</p>
